{% set name = "pymc3-ext" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymc3_ext-{{ version }}.tar.gz
  sha256: 2d552e44d3de884fa1a37d25b4f01b1e365ddf8e7d928c0fa266e805702d3ace

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - pymc3 >=3.9
    - aesara-theano-fallback >=0.0.2

test:
  imports:
    - pymc3_ext

about:
  home: https://github.com/exoplanet-dev/pymc3-ext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyMC3 Extras extracted from the "exoplanet" library
  doc_url: https://github.com/exoplanet-dev/pymc3-ext
  dev_url: https://github.com/exoplanet-dev/pymc3-ext

extra:
  recipe-maintainers:
    - dfm
